import JSZip from "jszip";
import tar from "tar-stream";
import * as Y from "yjs";

const WORKSPACE_KEY = "workspace";
const SOURCE_FILE_SUFFIX = ":app/page.tsx";

export type ExportProjectFiles = Record<string, string>;

export interface ExportSnapshotInput {
  projectId: string;
  pageCode: string;
  irSnapshot?: string | null;
}

function getFirstSourceText(doc: Y.Doc): Y.Text | null {
  const share = (doc as unknown as { share?: Map<string, Y.AbstractType<Y.Doc>> }).share;
  if (!share) {
    return null;
  }

  for (const key of share.keys()) {
    if (key.startsWith("source:") && key.endsWith(SOURCE_FILE_SUFFIX)) {
      return doc.getText(key);
    }
  }

  return null;
}

export function readPageCodeFromDoc(doc: Y.Doc): string {
  const workspace = doc.getMap(WORKSPACE_KEY) as Y.Map<unknown>;
  const workspaceCode = workspace.get("code");
  if (typeof workspaceCode === "string" && workspaceCode.trim().length > 0) {
    return workspaceCode;
  }

  const sourceText = getFirstSourceText(doc);
  if (sourceText) {
    const code = sourceText.toString();
    if (code.trim().length > 0) {
      return code;
    }
  }

  return `import React from "react";

export default function Home() {
  return (
    <main className="min-h-screen grid place-items-center p-16">
      <section className="max-w-3xl rounded-3xl border border-slate-200 bg-white p-10 shadow-xl">
        <h1 className="text-4xl font-bold text-slate-900">Exported from WebBuilder</h1>
        <p className="mt-4 text-slate-700">Start editing src/app/page.tsx and deploy when ready.</p>
      </section>
    </main>
  );
}`;
}

export function buildProjectFiles(pageCode: string): ExportProjectFiles {
  const normalizedPageCode = pageCode.endsWith("\n") ? pageCode : `${pageCode}\n`;

  const packageJson = {
    name: "webbuilder-export",
    private: true,
    version: "0.1.0",
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start"
    },
    dependencies: {
      next: "15.3.2",
      react: "19.0.0",
      "react-dom": "19.0.0"
    },
    devDependencies: {
      "@types/node": "^22.15.17",
      "@types/react": "^19.1.2",
      "@types/react-dom": "^19.1.2",
      autoprefixer: "^10.4.21",
      postcss: "^8.5.3",
      tailwindcss: "^3.4.17",
      typescript: "^5.8.3"
    }
  };

  return {
    "package.json": JSON.stringify(packageJson, null, 2) + "\n",
    "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true\n};\n\nmodule.exports = nextConfig;\n",
    "tailwind.config.js": "module.exports = {\n  content: [\"./src/**/*.{js,ts,jsx,tsx}\"],\n  theme: {\n    extend: {}\n  },\n  plugins: []\n};\n",
    "postcss.config.js": "module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {}\n  }\n};\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "es2022"],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }]
        },
        include: ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx"],
        exclude: ["node_modules"]
      },
      null,
      2
    ) + "\n",
    "next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file should not be edited\n",
    "src/app/globals.css": "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
    "src/app/layout.tsx": "import \"./globals.css\";\nimport type { ReactNode } from \"react\";\n\nexport const metadata = {\n  title: \"WebBuilder Export\",\n  description: \"Generated by WebBuilder\"\n};\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n",
    "src/app/page.tsx": normalizedPageCode
  };
}

export function getProjectFilesFromDoc(doc: Y.Doc): ExportProjectFiles {
  return buildProjectFiles(readPageCodeFromDoc(doc));
}

export async function exportProject(doc: Y.Doc): Promise<Buffer> {
  return exportProjectFromFiles(getProjectFilesFromDoc(doc));
}

export async function exportProjectFromFiles(files: ExportProjectFiles): Promise<Buffer> {
  const zip = new JSZip();
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content);
  }

  return zip.generateAsync({ type: "nodebuffer" });
}

export async function createProjectTarball(files: ExportProjectFiles): Promise<Buffer> {
  const pack = tar.pack();

  for (const [name, body] of Object.entries(files)) {
    pack.entry({ name }, body);
  }

  pack.finalize();

  const chunks: Buffer[] = [];
  for await (const chunk of pack) {
    chunks.push(Buffer.from(chunk));
  }

  return Buffer.concat(chunks);
}

export function createDocFromSnapshot(input: ExportSnapshotInput): Y.Doc {
  const doc = new Y.Doc();
  const workspace = doc.getMap(WORKSPACE_KEY);
  const sourceText = doc.getText(`source:${input.projectId}:app/page.tsx`);

  sourceText.insert(0, input.pageCode);
  workspace.set("code", input.pageCode);

  if (input.irSnapshot) {
    workspace.set("ir", input.irSnapshot);
  }

  return doc;
}
